mailer:
  smtp:
    address: smtp.gmail.com
    port: 587
    domain: example.com
    user_name: ruby.test.job
    password: ruby-test-job-passwd
    authentication: plain
    enable_starttls_auto: true